-- Era OS Database Migration
-- Add task origin tracking for roadmap-driven task generation
-- Version: 002_task_origin

BEGIN;

-- Add origin column to tasks table
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS origin TEXT NOT NULL DEFAULT 'manual' CHECK (origin IN ('generated', 'manual'));

-- Add category column for better task classification
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS category TEXT DEFAULT 'practice' CHECK (category IN ('practice', 'learning', 'project', 'review', 'ctf', 'documentation', 'automation'));

-- Add source_template for generated tasks tracking
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS source_template TEXT;

-- Add generation_date to track when task was generated
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS generation_date DATE;

-- Add generation_context JSONB for audit/debug
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS generation_context JSONB;

-- Update indexes
DROP INDEX IF EXISTS idx_tasks_status_pillar;
CREATE INDEX idx_tasks_origin ON tasks(origin);
CREATE INDEX idx_tasks_status_pillar ON tasks(status, pillar);
CREATE INDEX idx_tasks_origin_status ON tasks(origin, status);
CREATE INDEX idx_tasks_generation_date ON tasks(generation_date) WHERE generation_date IS NOT NULL;

-- Backfill existing tasks as manual
UPDATE tasks SET origin = 'manual' WHERE origin = 'generated';
UPDATE tasks SET category = 'practice' WHERE category IS NULL;

-- Add comment for documentation
COMMENT ON COLUMN tasks.origin IS 'Task origin: generated (from roadmap) or manual (user-created)';
COMMENT ON COLUMN tasks.category IS 'Task category for classification and filtering';
COMMENT ON COLUMN tasks.source_template IS 'Reference to the roadmap template that generated this task';
COMMENT ON COLUMN tasks.generation_date IS 'Date when the task was generated by the system';
COMMENT ON COLUMN tasks.generation_context IS 'Context used when generating this task (JSON)';

COMMIT;

-- Verify migration
SELECT 'tasks.origin column added' as status, 
       count(*) as manual_tasks 
FROM tasks WHERE origin = 'manual';